export global Theme {
    out property <color> background: #13131b;
    out property <color> surface: #13131b;
    out property <color> surface_dim: #13131b;
    out property <color> surface_bright: #393841;
    out property <color> surface_container_lowest: #0d0d15;
    out property <color> surface_container_low: #1b1b23;
    out property <color> surface_container: #1f1f27;
    out property <color> surface_container_high: #292932;
    out property <color> surface_container_highest: #34343d;
    out property <color> surface_variant: #34343d;

    out property <color> primary: #c0c1ff;
    out property <color> on_primary: #1000a9;
    out property <color> primary_container: #8083ff;
    out property <color> on_primary_container: #0d0096;
    out property <color> inverse_primary: #494bd6;

    out property <color> secondary: #4edea3;
    out property <color> on_secondary: #003824;
    out property <color> tertiary: #ffb783;
    out property <color> error: #ffb4ab;
    out property <color> on_error: #690005;

    out property <color> on_surface: #e4e1ed;
    out property <color> on_surface_variant: #c7c4d7;
    out property <color> outline: #908fa0;
    out property <color> outline_variant: #464554;
}
